Skip to content
This repository
Search
Pull requests
Issues
Gist
 @huangboju
 Unwatch 1
  Star 0
  Fork 0 huangboju/Libertine
 Code  Issues 0  Pull requests 0  Projects 0  Wiki  Pulse  Graphs  Settings
Branch: master Find file Copy pathLibertine/.swiftlint.yml
3b29db5  15 days ago
@huangboju huangboju Update .swiftlint.yml
1 contributor
RawBlameHistory     
53 lines (52 sloc)  1.49 KB
disabled_rules: # rule identifiers to exclude from running
  - cyclomatic_complexity
  - fixme
  - function_body_length
  - function_parameter_count
  - todo
  - valid_docs
  - variable_name
  - type_name
opt_in_rules: # some rules are only opt-in
  #- empty_count
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - Source
  - HYAlertController/HYAlertControllerDemo/HYAlertControllerDemo
excluded: # paths to ignore during linting. Takes precedence over `included`.
  # - Carthage
  # - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 400 #
# they can set both implicitly with an array
type_body_length:
  - 300 # warning
  - 400 # error
# or they can set both explicitly
file_length:
  warning: 500
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 2 # only warning
  max_length: # warning and error
    warning: 40
    error: 50
  excluded: iPhone # excluded via string
variable_name:
  min_length: 1 # only min_length
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle)
Contact GitHub API Training Shop Blog About
© 2016 GitHub, Inc. Terms Privacy Security Status Help
